config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :portfolios, :services, :articles

  resources :welcome, path: :contact, only: %i[index create]

  root 'welcome#index'
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index
    @contact = Contact.new
    @admin = User.find_by_admin(:true)
    @publications = @admin.publications
  end

  def create
    @contact = Contact.new(contact_params)
    if verify_recaptcha(model: @contact) && @contact.save
      render :index, notice: 'Thank you, your message was delivered.'
    else
      render :index, alert: 'Sorry, your message was not delivered.'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end
end

app/views/welcome/create.js.erb
/* Replace html on welcome-index view. */
// clean form fields after contact info was sent
$("#contact_name").val("")
$("#contact_email").val("")
$("#contact_message").val("")

// reset reCAPTCHA after comment was created
grecaptcha.reset();

app/views/welcome/index.html.haml
<!-- ========= PRESENTATION ========= -->
%header#home.jumbotron.bg-image.vertical-center
  .container
    .row
      .col-sm-12.text-col.text-center
        %h1= "Hi, I am #{@admin.first_name} #{@admin.last_name}"
        %p software engineer

<!-- ========= SERVICES ========= -->
%section#services.white-bg.padding-top-bottom
  .container
    %header.section-header.text-center
      %h1.scrollimation.scale-in What I Do
      %h3
        I am passionate about providing solutions that combine
        functionality, interaction and form to design for fitting user
        experiences that make people happy.
    .row.services
      - @publications[:services].each do |service|
        - cache service do
          .col-lg-3.col-md-6.col-sm-12.col-xs-12.item
            .icon
              = image_tag service.images.active.first.url, class: 'img-responsive img-center', alt: ''
            %h2= link_to service.title, service_path(service)
            %p= service.description

<!-- ========= ABOUT ========= -->
%section#about.dark-bg.light-typo.padding-top-bottom
  .container
    %header.section-header.text-center
      %h1 About Me
    .row
      .col-sm-4.col-sm-offset-4
        = image_tag user_image(@admin), class: 'img-responsive img-center img-circle', alt: ''
      .col-sm-10.col-sm-offset-1
        %p.text-center= @admin.presentation

<!-- ========= PORTFOLIO ========= -->
%section#work.gray-bg.padding-top-bottom
  .container
    .row
      %header.section-header.text-center
        %h1 My Works
        %h3
          I've been working on several projects.
          %br/
          See a collection of works I am proud of!
    .row
      #work-carousel.carousel.slide{ 'data-ride': 'carousel' }
        .carousel-inner{ role: 'listbox' }
          - @publications[:portfolios].each_with_index do |portfolio, index|
            - cache portfolio do
              %div{class: "#{index.zero? ? 'item active' : 'item'}"}
                .col-md-6.margin-btm-30
                  %h1= portfolio.title
                  %p= portfolio.description
                  %p
                    %strong Client:
                    = portfolio.client
                  %p
                    %strong Skills:
                    = portfolio.skills.map{|skill| skill.superpower}.join('/ ')
                  %p= link_to 'Visit Project', portfolio_path(portfolio), class: 'no_decoration black-button black-to-white'
                .col-md-6
                  = image_tag portfolio.images.active.first.url, class: 'img img-responsive', alt: ''
        %ol.carousel-indicators
          - @publications[:portfolios].each_index do |i|
            %li{class: "#{i == 0 and 'active' or ''}", 'data-target': '#work-carousel', 'data-slide-to': "#{i}" }

%section#all-works.dark-bg
  .container
    .row
      .col-md-8.col-md-offset-2.text-center
        %p.text-center
          = link_to portfolios_path, class: 'black-button white-to-black' do
            %i.fa.fa-rocket &nbsp;&nbsp; All my jobs

<!-- ========= BLOG ========= -->
%section#blog.white-bg.padding-top-bottom
  .container
    .row
      %header.section-header.text-center
        %h1 Latest News
        %h3
          I have worked with many serious brands in the Design and Code industry.
          %br/
          See a collection of works I am proud of!
    .row
      - @publications[:articles].each do |article|
        - cache article do
          - image_article = article.images.active.first.url
          .col-lg-4.col-md-12.col-sm-12.col-xs-12.item
            .col-md-12.nopadding-left.nopadding-right
              = link_to article_path(article) do
                .item-img-wrap.nopadding-left.nopadding-right
                  = image_tag image_article, class: 'img-responsive', alt: ''
            #blog-desc.col-md-12.nopadding-left.nopadding-right
              %h3= link_to article.title, article_path(article)
              %span= article.publication_date.strftime("%F")
              %p= article.shorten_description(144)
            #blog-desc-link.col-md-12
              %p.text-right= link_to 'Read More', article_path(article), class: 'no_decoration black-button black-to-white'

%section#all-articles.dark-bg
  .container
    .row
      .col-md-8.col-md-offset-2.text-center
        %p.text-center
          = link_to articles_path, class: 'black-button white-to-black' do
            %i.fa.fa-coffee &nbsp;&nbsp; All my articles

<!-- ========= CONTACT ========= -->
%section#contact_me.gray-bg
  .container
    .row.row-btm140
      %header.section-header.text-center
        %h1 Drop Me a Line
      = form_for @contact, url: welcome_index_path(@contact), as: :contact, remote: true, html: {class: 'contact-submit'} do |f|
        .form-group.col-xs-12.col-md-12
          = f.label :name, class: 'col-xs-12 col-sm-2 control-label'
          .col-sm-8.col-xs-12
            = f.text_field :name, class: 'form-control', placeholder: 'Name', required: true
        .form-group.col-xs-12.col-md-12
          = f.label :email, class: 'col-sm-2 control-label'
          .col-sm-8.col-xs-12
            = f.email_field :email, class: 'form-control', placeholder: 'Email', required: true
        .form-group.col-xs-12.col-md-12
          = f.label :message, class: 'col-sm-2 control-label'
          .col-sm-8.col-xs-12
            = f.text_area :message, class: 'contact-textarea', required: true
            .col-sm-6.col-xs-6.nopadding-left
              = recaptcha_tags
            .col-sm-6.col-xs-6.nopadding-right
              = f.submit 'Send Message', class: 'black-button black-to-white', style: 'float: right;'